### ISSUE TITLE
no french language in the list of voice

### ISSUE THREAD

**Issue by beta001aer** [HueVirtualCreature/HuesSTTTSSystem#5]
hi, i don't see any french language in the list of voice of Hue's STTTS System it's normal ? 
![image](https://github.com/HueVirtualCreature/HuesSTTTSSystem/assets/124807963/d58f282c-091d-44d7-a7d9-637d3fff5353)

**Comment by HueVirtualCreature** [comment]
@beta001aer Can you look now? I believe the updates should have deployed by now

**Comment by beta001aer** [comment]
perfect thanks
